---
Name: firesphere-jwt-injections
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\AuthenticationHandler:
    properties:
      Handlers:
        jwt: '%$Firesphere\GraphQLJWT\Authentication\JWTAuthenticationHandler'
  Firesphere\GraphQLJWT\Authentication\JWTAuthenticationHandler:
    properties:
      JWTAuthenticator: '%$Firesphere\GraphQLJWT\Authentication\JWTAuthenticator'
  Silverstripe\Security\MemberAuthenticator\MemberAuthenticator:
    class: Firesphere\GraphQLJWT\Extensions\ExtendedMemberAuthenticator
